### ISSUE TITLE
Support name and description on the programs domain

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#102]
Currently the program domain does not support the name or description properties / columns on program, but rather always delegates the population of these to the associated Concept.

Implementations should be able to choose whether or not they prefer to populate these fields by adding explicit Name and/or Description columns.  These columns, if present, would supercede values from Concept.  These columns would be optional, and the current behavior would be the default if they are left unspecified.

**Comment by mks-d** [comment]
Thanks a bunch @mseaton for your PR.
