### ISSUE TITLE
Order Type Domain is unable to save Order Types that refer to custom classes

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#116]
The OrderTypeLineProcessor includes validation to test that the specified java_class_name property is in fact a valid Java class.  However,this fails if the Order Type in question refers to a Java class that the Initializer module is unaware of.

This is the code in question:

```
if (!StringUtils.isEmpty(javaClassName)) {
	try {
		Class.forName(javaClassName);
	}
	catch (ClassNotFoundException e) {
		throw new IllegalArgumentException(
				      "'" + javaClassName + "' does not represent a valid Java or OpenMRS class.", e);
	}
	orderType.setJavaClassName(javaClassName);
}
```

In our PIH system, we are attemping to migrate over to Initializer and have an order type that has a custom Java class defined in the radiology module (org.openmrs.module.radiologyapp.RadiologyOrder).  This fails to validate, and thus fails to save due to the above code block.

**Comment by mseaton** [comment]
PR raised for this.  @mks-d this is a blocker for our ability to use Iniz for order types.

**Comment by mks-d** [comment]
Thanks @mseaton.

Why did it fail in your env, is it because this 'radiologyapp' module hasn't started when Iniz is loading the config?

**Comment by mseaton** [comment]
@mks-d I don't think it has to do with the loading order.  Initializer isn't aware of the radiology module, so wouldn't have this class on the classpath.  Regardless, just using Class.forName, without specifying the Classloader to use, probably will have unpredictable results in an OpenMRS environment.  Do you feel strongly about keeping this validation in place?  I guess the alternative would be to add the radiology module as an aware_of dependency, but this doesn't feel like a scalable approach, and likely to run into this same issue with another class/module down the road.

**Comment by mks-d** [comment]
@mseaton no I wasn't feeling strongly about this, I just wanted to understand a bit better where this was coming from.

I guess it's all fine and the order API will fail appropriately when this Java class name is a bogus string. So all good 👍

**Comment by mseaton** [comment]
Thanks @mks-d !!
