### ISSUE TITLE
Concept Source domain needs to support hl7Code and uniqueId

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#121]
The recently implemented Concept Source domain omitted support for the "hl7Code" and "uniqueId" properties of ConceptSource.

At minimum we need to support hl7Code.  While we are at it, we should support uniqueId if it is straightforward (it was added in OpenMRS 2.1.0)

**Comment by mseaton** [comment]
@mks-d - this is ready for a quick review if you can find a moment.  @brandones FYI, as this relates to the domain you recently added.

**Comment by mks-d** [comment]
Thanks a bunch @mseaton!
