### ISSUE TITLE
Add support for "initializer.include.[domain]" runtime properties

### ISSUE THREAD

**Issue by mogoodrich** [mekomsolutions/openmrs-module-initializer#132]
The runtime properties configuration of Iniz provides support for a "initializer.exclude.[domain]" properties. For example, from the documentation:

`initializer.exclude.concepts=*diags*,*interventions*`

This tells iniz, when parsing the "concepts" directory, to exclude all files that match the wildcard patterns specified.

We'd like to support an equivalent "include" function, ie:

`initializer.exclude.concepts=*diags*,*interventions*`

... would *only* include files that contain "diags" and "interventions" in the name.

If *both* an inclusion and an exclusion pattern is provided, the inclusion is processed first, for example:  including “*.csv” and excluding “f*” would give you all CSVs that don’t start with an f.

Note that when we implement this, we want to make the method to do this publicly accessible, as some implementations (PIH) access the Loader API methods directly.  

Currently, the Loader provides a method with a signature:

https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/api/src/main/java/org/openmrs/module/initializer/api/loaders/Loader.java#L42

Likely, we should add a method:

`void loadUnsafe(List<String> wildcardExcludes, List<String> wildcardIncludes, boolean doThrow) throws Exception;`

**Comment by mseaton** [comment]
My sense is that this is not something we need at the moment, and we could close this out until (if) we do.  @mogoodrich ?

**Comment by mogoodrich** [comment]
I don't remember the exact use case we needed, but, yeah, since it's 1.5 years old now seems fine to close and reopen again at a later date if needed.
