### ISSUE TITLE
DisplaysCsvParser causes all rows with retired/voided data to fail with an exception

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#154]
The implementation of the DisplaysCsvParser that was recently introduced in #95 has the following implementation in its boostrap(CsvLine) method ([here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/81756c905ca27b10e643b88411628a1a486af778/api/src/main/java/org/openmrs/module/initializer/api/display/DisplaysCsvParser.java#L40-L43)):

```java
public OpenmrsObject bootstrap(CsvLine line) throws IllegalArgumentException {
    if (BaseLineProcessor.getVoidOrRetire(line)) {
        throw new APIException("A voided or retired object cannot be internationalized. "
                + "Check the implementation of this parser: " + getClass().getCanonicalName());
    }
    
    return bootstrapParser.bootstrap(line);
}
```

The result of this is that for any CSV domains that contain rows with Voided or Retired data, the pre-loader will fail for these rows by throwing an Exception.

Now, when Initializer is configured to ignore exceptions that occur on a given row (which is the default, out of the box behavior), this does not result in any real issues, as failures will happen during pre-loading, and processing will happily continue and the actual row loading will work.  And since this is how every unit test in the module is configured to run as well, this issue did not present itself during development.   Still, these row issues are reported and you can see them if you inspect row errors, which is not ideal, since you really want these row errors to consist of actual problems that need to be dealt with, not background non-issues.

However, more concerningly, once you start running Initializer with stricter loading rules, this starts to fail.  Indeed, this new version of Initializer fails to load any of our distributions at PIH, which all have voided / retired rows and which we load in "strict" mode.

The issues can be reproduced by either:

a) Using loader.loadUnsafe(null, true) - i.e. in a unit test, as an alternative to loader.load()

-or-

b) Setting the runtime property:  `initializer.startup.load = fail_on_error`

For example, go into EncounterTypesLoaderIntegrationTest#load_shouldLoadEncounterTypesAccordingToCsvFiles and change the first ine from `loader.load()` to `loader.loadUnsafe(null, true)` and you will see this unit test fail.  And running it as-is will also show a row error in the log, even though the unit test passes.

Taking a step back, it isn't really clear to me _why_ we have this restriction in place.  Why exactly is it not permitted to localize a retired or voided row?  Whether or not this is the right decision, we certainly do not want to fail processing when this situation is encountered, and the pre-loader implementation needs to find a way to either process voided/retired data, or skip voided/retired rows without throwing an Exception.

@Ruhanga / @mks-d - this is something we will need addressed, either by reverting #95 or by finding a way to fix it.

**Comment by mks-d** [comment]
@mseaton oversight from my part as I did not review this specific part of the preloader.

@Ruhanga what was the rationale here? Why wouldn't we let the preloaders run on voided/retired entities? It's "underperforming", admittedly, but not functionally harmful. Alternatively we could decide to not preload a voided/retired entities, as in make their preloader do nothing.

**Comment by Ruhanga** [comment]
Thanks @mseaton for providing feedback. Nice catch on the fact that the PR missed the `strict` mode when loading i18n messages. At the time/till now, because of every call to `DisplaysPreLoader.load` having to go through [this method definition](https://github.com/mekomsolutions/openmrs-module-initializer/blob/74a2907d2c10e4641f1ec3e7620f0059ddce2484/api/src/main/java/org/openmrs/module/initializer/api/CsvParser.java#L216-L253) flow, there was 1.) a problem of having to retire an object way early before it had to, 2.) not being able to retrieve either name or uuid needed for i18n on the object.  I do agree indeed that this should not mean to fail the entire loading of metadata when in strict mode. I'd then suppose that [pre-loaders](https://github.com/mekomsolutions/openmrs-module-initializer/blob/81756c905ca27b10e643b88411628a1a486af778/api/src/main/java/org/openmrs/module/initializer/api/loaders/BaseFileLoader.java#L71) should be rather light weight and they would not have to throw errors in the end. This would imply doing something like `preload(f, false)` from the latter link shared. @mks-d thoughts...

**Comment by mks-d** [comment]
Agreed with @Ruhanga with the idea of `preload(f, false)`.
However after speaking together him and I, we decided that preloaders would basically not throw by default, but an overloadable method would be made available to change this behaviour for other preloaders if needed. In the end we would end up with something like `preload(f, isThrowingPreloader(doThrow))`.

So `BaseCsvLoader#isThrowingPreloader(bool)` would always return `false`, but this wouldn't have to be the case for other preloaders, if warranted.

**Comment by mseaton** [comment]
@Ruhanga just checking in on the status of this ticket?

**Comment by Ruhanga** [comment]
Thanks for the followup @mseaton. I'm to push an update on the PR. Sorry this has come in a little late after a conversation with @mks-d on the changes to introduce. The associated PR is likely mergeable by end of tomorrow.

**Comment by mks-d** [comment]
@mseaton this should be fixed, could you confirm when you get a chance?

**Comment by mseaton** [comment]
@mks-d and @Ruhanga - thanks, this does seem to work now.  My only gripe is that I could do without the (misleading) errors in the logs like these:

```
ERROR - BaseCsvLoader.lambda$load$0(117) |2021-11-17 18:37:05,111| An OpenMRS object could not be constructed or saved from the following CSV line:
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+
| Uuid                                 | Void/Retire | Workflow                             | State concept         | Initial | Terminal |
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+
| 2332EC51-80CF-4FB4-88E1-9B74427BAC1E |        true | aba55bfe-9490-4362-9841-0c476e379889 | PIH:TREATMENT STOPPED |    true |          |
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+
org.openmrs.api.APIException: A voided or retired object cannot be internationalized. Check the implementation of this parser: org.openmrs.module.initializer.api.display.DisplaysCsvParser
	at org.openmrs.module.initializer.api.display.DisplaysCsvParser.bootstrap(DisplaysCsvParser.java:42)
	at org.openmrs.module.initializer.api.CsvParser.initialize(CsvParser.java:225)
	at org.openmrs.module.initializer.api.CsvParser.process(CsvParser.java:196)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.load(BaseCsvLoader.java:99)
	at org.openmrs.module.initializer.api.loaders.BaseInputStreamLoader.load(BaseInputStreamLoader.java:39)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.preload(BaseCsvLoader.java:72)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.preload(BaseFileLoader.java:51)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.lambda$loadUnsafe$1(BaseFileLoader.java:82)
...
ERROR - BaseFileLoader.preload(54) |2021-11-17 18:37:05,112| 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
+-+-+-+-- BEGINNING OF CSV FILE ERROR SUMMARY --+-+-+-+
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
programworkflowstates.csv ('displays' domain) was processed and 1 out of 21 entities were not saved.
The CSV line(s) corresponding to those entities are listed below:
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+
| Uuid                                 | Void/Retire | Workflow                             | State concept         | Initial | Terminal |
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+
| 2332EC51-80CF-4FB4-88E1-9B74427BAC1E |        true | aba55bfe-9490-4362-9841-0c476e379889 | PIH:TREATMENT STOPPED |    true |          |
+--------------------------------------+-------------+--------------------------------------+-----------------------+---------+----------+

Paste print for spreadsheets... etc:

Uuid,Void/Retire,Workflow,State concept,Initial,Terminal
2332EC51-80CF-4FB4-88E1-9B74427BAC1E,true,aba55bfe-9490-4362-9841-0c476e379889,PIH:TREATMENT STOPPED,true,
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
+-+-+-+-+--  END OF CSV FILE ERROR SUMMARY  --+-+-+-+-+
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

```

Can we do something about this?  It's possible that one of my recent commits for another issue expanded the error logging in the module so these now show up more frequently.  I admit, there are things happening with logging in the module that I don't understand (and which I've ticketed separately).

**Comment by Ruhanga** [comment]
Thanks for confirming the fix works for you @mseaton. I'd somewhat bend towards having clear, generic and yet comprehensive logging [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/a10d37e6990827edf37a60a4c51c3fe76d3978f9/api/src/main/java/org/openmrs/module/initializer/api/loaders/BaseCsvLoader.java#L133-L134). Something along the lines `file.getName() + " ('" + getDomainName() + "' domain) was processed and " + errLines.size() + " out of " + totalCount + " entities were not successfully processed/saved."` or maybe a better log could be suggested. Thoughts @mseaton, @mks-d??

**Comment by mseaton** [comment]
@Ruhanga thanks, I'm not entirely sure what you are suggesting?  My (relatively strong) opinion is - if an error didn't happen, don't log an error.  The fact that these pre-loaders throw an exception is an implementation detail that does not reflect a true error state, and should not appear in the logs.

**Comment by mks-d** [comment]
I think we will have to find a way for treating pre-loaders errors as, at worst, warnings.

And also change the messages, because those shared by @mseaton suggest that the entity could not be loaded, which is not accurate (maybe that's what you suggested @Ruhanga?)

**Comment by Ruhanga** [comment]
Yes @mks-d, thanks. IMO it'd be ideal to keep some form of logs on lines failing on preload and not entirely discarding them as this could probably make it difficult to determine why they were not preloaded. Perhaps logging them as warnings as suggested by @mks-d.

**Comment by mseaton** [comment]
@Ruhanga the main issue is that the code is throwing errors saying that lines are failing, when in fact lines are not failing and there should be no errors.  If the preloader is not a throwing preloader, then I think the implication is that it would not throw errors, right?  I'm fine with some trace logging in case someone wants to better see what's happening in the logs, but not warn level logging, and let's make it clear that it isn't an error loading the lines.

**Comment by mseaton** [comment]
@Ruhanga I think if we just keep the principle that errors should be handled and logged as errors, and non-errors should not be handled or logged as errors, we'll be in good shape.

**Comment by mks-d** [comment]
@mseaton to the best of your recollection, can we close this issue?

**Comment by mseaton** [comment]
@mks-d yes, I believe this can be closed.  Thanks for following up.
