### ISSUE TITLE
Message properties do not always return correct messages

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#155]
We have recently been using the messageproperties domain quite a bit as a means to deliver all of our translations across our distributions.  Over the course of this time, we have noticed some inconsistent behavior, and finally had a chance to take a look at it.  There are a few issues that we have discovered.  In summary those issues are:

1. The InitializerMessageSource does not default to the system locale if no message is found in the specified locale.  Specifically, if there is a translation present in messages_en.properties, and this translation is not present in messages_fr.properties, when someone using the system in French views this message they will see the message code rather than the English translation.  This is inconsistent with the core Message Source (and what we typically expect).

2. The InitializerMessageSource does not correctly handle a situation where the parent source has a "better" translation than the InitializerMessageSource.  For example, if the parent (the OpenMRS message source) has a message code defined for "fr_FR", and the Initializer source has the same message code defined for "fr", when someone uses the system in the "fr_FR" locale, they will get the less-specific Initializer "fr", rather than the more-specific parent translation.

The InitializerMessageSource needs to be modified to account for these issues.  Having spent some time looking at the code in depth, my belief is that the best course of action for a solution is to write a comprehensive Message Source that does not defer to the OpenMRS message source as parent, but rather re-implements the OpenMRS message source with additional Initializer functionality included.  If successful, this could ultimately be harvested back into OpenMRS core in a way that would allow Initializer (and other modules) to plug into it and extend it.

@mks-d FYI.

**Comment by Ruhanga** [comment]
Thanks @mseaton for looking into this. No objections from me.

**Comment by mogoodrich** [comment]
I haven't reviewed, but your proposal makes sense to me.  To clarify, when you say "system locale" do you mean the locale defined by the "default_locale" global property?

**Comment by mseaton** [comment]
> To clarify, when you say "system locale" do you mean the locale defined by the "default_locale" global property?

No, I mean whatever is returned by Locale.getDefault() from the JDK, which I assume is a server locale.  This is what I've seen used elsewhere.

But this does bring up a good point, and I had also been thinking something along these terms in relation to the overall message cache that we maintain in memory - namely, should this use the default_locale global property as the "fallback" locale instead of (or prior to) using Locale.getDefault()?  And should we only actually worry about processing message codes that match those in the locale.allowed_list global property?  (No use keeping messages for dozens of languages the server will never use in memory).  Interested in your thoughts @mogoodrich and @mks-d ...
