### ISSUE TITLE
Support for cohort types, cohort attribute types and cohort member attribute types.

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#160]
[TBC] and also see https://github.com/openmrs/openmrs-module-cohort

**Comment by rbuisson** [comment]
Hi @ibacher @mks-d , I see the need for Cohort Type, but I am not sure about Cohort Attribute Type and Cohort Member Attribute.
Is there a use case behind this? If so, how urgent?

**Comment by ibacher** [comment]
Cohort Attribute Type (and hence Cohort Attributes) would be the obvious place to store the filters / criteria that define a a dynamic cohort.

I don't really have an obvious or immediate use-case for Cohort Member Attribute Type, but it's not likely to be very challenging to implement.

**Comment by mks-d** [comment]
AFAIK the support for cohort-related metadata was developed and is sufficiently supported by Iniz.
