### ISSUE TITLE
OpenConceptLabLoader must support predictable and configurable order of file loading

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#174]
Currently, the OpenConceptLabLoader extends BaseFileLoader, and inherits the default implementation of BaseFileLoader.toOrderedFile(File file).  This default implementation does not guarantee any particular order, but rather treats all files as the same order (all have order == Integer.MAX_VALUE).  Further, the default "compareTo" implementation of OrderedFile does not fall back to the natural ordering of File, but only uses this Order property.  Thus loading is likely to be unpredictable.

This ticket is for updating the OpenConceptLabLoader to support a more predictable ordering in the event that more than one OCL collection zip is present in the domain.

Proposal:

Override toOrderedFile(File) in OpenConceptLabLoader.  Each ordered file should compare itself to another file based on these criteria:

1. Support configuring order with a new file in the domain named "_order" (eg. .OpenMRS/configuration/ocl/_order).  If this file is found, parse this into a List<String> of filenames (one filename per line, where filename represents the relative path within the domain and could be nested in a subfolder).  Files would be loaded in the order specified.  If a particular file is not specified, it would be ordered after those that are specified.

2. If no "_order" file is present, or if there are files not specified in the "_order" file, then this should fall back to comparing two files based on their filename (again, filenames are relative to the ocl domain and could contain subfolder paths).

The result of this proposal is that:

a) By default, with no additional configuration, files will be loaded in a predictable order based on sorted filename.
b) Implementations can configure specific ordering as needed, for example if they prefer to maintain the filenames generated by OCL

@mks-d / @ibacher does this sound acceptable?

**Comment by ibacher** [comment]
That sounds fine. I'd almost rather implement part 2 as part of the BaseFileLoader itself, i.e., to ensure that file loading is always in a predictable order. I suspect, though, that the default order is not random but based on filesystem ordering, but it would be good to guarantee that.

**Comment by mogoodrich** [comment]
Works for me... @mks-d we may work on this in the next sprint, any objections?

**Comment by mseaton** [comment]
@mks-d / @ibacher - I have a PR up for review here to solve this:  #176 

I wasn't thrilled with the _order file idea that I presented in part 1 above, and ended up just implementing part 2 as @ibacher suggested in a way that would work for the BaseFileLoader generally - namely, to make a small modification to the compareTo method of OrderedFile to compare based on the file absolute path as a secondary ordering method.

Ultimately, I think this will meet our needs in that we will have a mechanism to achieve predictable and configurable loading of files, by simply controlling the filenames in the domain.  This will get us going, and we can assess whether any further configuration options would help down the road if necessary.

Can I get a quick review on this?
