### ISSUE TITLE
Support loading AMPATH forms translation files

### ISSUE THREAD

**Issue by rbuisson** [mekomsolutions/openmrs-module-initializer#180]
AMPATH Forms translations should be loaded into the backend, ideally linked to each form. These translations are JSON documents that associate label keys with a language-specific translation.

The JSON documents should be saved as a FormResource so they are linked to the form and given a name like `<form_name>_translations_en`, so that we can easily identify them.

**Comment by rbuisson** [comment]
Some conversations happening on this JIRA ticket too: https://issues.openmrs.org/projects/O3/issues/O3-614?filter=allopenissues

**Comment by mks-d** [comment]
@rbuisson @Ruhanga what's the status of this one?

**Comment by delphinepas** [comment]
@ibacher @Ruhanga is there any update on this topic cc @icrc-jofrancisco @icrc-fdeniger @gracepotma

**Comment by ibacher** [comment]
This piece of functionality is complete.
