### ISSUE TITLE
Reloading Concept CSVs should not clear Member and Answers if those columns aren't in the CSV

### ISSUE THREAD

**Issue by mogoodrich** [mekomsolutions/openmrs-module-initializer#198]
We added support for concept sets domain here:

https://github.com/mekomsolutions/openmrs-module-initializer/issues/140

We should now implement the functionality suggested in a comment at the end of that ticket:

"One thought I had was that, if a "concepts.csv" domain file has an "Answers" or "Members" column defined, and if that column is empty for a given Concept row, then clear existing Answers/Members as appropriate. If the CSV does not have this column, do nothing. But if the CSV has the column and a Concept leaves values blank, then infer that this means it should have no members/answers. Thoughts on this modification?"

Currently, I believe that whenever a concept file is reloaded, all the members/answers are reloaded *regardless* of whether or not the Member or Answers column is present (note: I've tested this behavior for members, but not for answers).

This is incredibly dangerous, because when using the concepts.csv + concept_sets.csv module, then any time a change is made to a concepts.csv file, *all* concepts are removed from any sets or answered in that file unless a corresponding change happens to be made to the set files for all the concepts in that csv.

fyi @mseaton

**Comment by mseaton** [comment]
PR merged, closing this out.
