### ISSUE TITLE
Concepts should be fetched by FSN only

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#211]
####  1) Background

See
* [Initializer: Matching Concepts by Name and the OpenMRS getConceptByName method ](https://talk.openmrs.org/t/initializer-matching-concepts-by-name-and-the-openmrs-getconceptbyname-method/37413?u=mksd)

####  2) Dev Notes
This happens [here](https://github.com/mekomsolutions/openmrs-module-initializer/blob/17c0420214e8f2a72e3bda1be370da3eff6c1f4a/api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java#L180) in `Utils#fetchConcept`.

####  3) Proposed Solution
After exposing failing unit tests that demonstrate that `ConceptService#getConceptByName` produces unreliable results, proceed to introduce a new method/service layer/DAO layer hosted in Iniz that ensures that only FSNs are being searched. This could largely be created on the same premises of the existing code, see [here](https://github.com/openmrs/openmrs-core/blob/de56986f5a788c551666e41ac2f2d100a19d7041/api/src/main/java/org/openmrs/api/db/hibernate/HibernateConceptDAO.java#L1752-L1767) in `ConceptService`'s DAO layer.

**Comment by mseaton** [comment]
@mks-d when we do this, let's get rid of the hacky code that iterates over all of the Locales and sets the Context locale, in order to be able to search by concept in that locale.  Let's just create a DAO/Service method that will search by FSN without consideration of Locale.

**Comment by mks-d** [comment]
@ibacher / @Ruhanga – what about this one?

**Comment by ibacher** [comment]
Looks to me like it's implemented.
