### ISSUE TITLE
Add Support for Drug Reference Maps

### ISSUE THREAD

**Issue by mogoodrich** [mekomsolutions/openmrs-module-initializer#219]
Drugs in OpenMRS can be mapped to reference terms in the same manner as Concepts (see Drug Reference Map in orders)

We should support this in Iniz as follows:

In the Drugs domain, support specifying mapping in the same was we do for concepts as described here:

https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/concepts.md   (see "Mapping Headers" section... we will support the new recommended format "Mappings|SAME-AS" aod "Mappings|SAME-AS|Source" format)

@mks-d  @ibacher @mseaton @rbuisson  fyi... any thoughts? At PIH we need this and can likely build this out in the coming weeks.

**Comment by mks-d** [comment]
Thanks @mogoodrich - I will let others comment in more details but if this is
1. Useful to PIH
2. Backward compatible (looks like it would be)
3. Documented in the README(s)

then we are welcoming this suggested improvement. Depending on the timing this would make it in 2.5.0 or 2.6.0.

**Comment by ibacher** [comment]
This seems like an excellent addition to me!

**Comment by mogoodrich** [comment]
Yes, @mks-d  all three of those things will be true, thanks!

**Comment by mseaton** [comment]
I ran into a bit of a snag here.  See https://issues.openmrs.org/browse/TRUNK-6164.  Will need to discuss how to work around this in Initializer.  @ibacher  FYI

**Comment by mseaton** [comment]
I have a solution for this ready for review @ibacher .  Unfortunately the PR is failing in Github Actions because it depends on the latest 2.3.x build, and OpenMRS CI is failing to build 2.3.x due to Bamboo issues.  Once we resolve that, things should turn green.
