### ISSUE TITLE
Not able to set a `Location` person attribute

### ISSUE THREAD

**Issue by riteshghiya90** [mekomsolutions/openmrs-module-initializer#243]
sample entry in personattributetypes/registration_pat.csv:

```csv
Uuid,Void/Retire,Name,Description,Format,Foreign uuid,Searchable,_order:1000
113f9a02-f4ac-11ed-a05b-0242ac120003,,registrationLocations,,org.openmrs.Location,0fbbeaf4-f3ea-11ed-a05b-0242ac120002,,
```

Here the uuid refers to one of the location uuid.
When we start openmrs with this configuration then person attribute is being added with foreign key as **0**.

**Comment by mks-d** [comment]
@riteshghiya90 apologies about the super late reaction here. Could you share the error message that you got?

**Comment by mks-d** [comment]
@riteshghiya90 you have run into a bug that was solved by [TRUNK-6242](https://openmrs.atlassian.net/browse/TRUNK-6242).

You would have to upgrade OpenMRS Core to version `2.7.0` or above to resolve the issue you have faced.
