### ISSUE TITLE
Support explicit `addresshierarchy` domain.

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#252]
Introduce an `addresshierarchy` (AH) domain that takes care of:
1. Load all AH-related configs (address template, address entries, etc).
1. Filling the Ext I18n's i18n reverse cache.

This work will demand for Iniz to become aware of AH:
* Let's release AH 2.15.3 and bump it to AH 3.0.0.
  * Iniz will depend and be aware of AH 3.0.0.
* AH 3.0.0 will not support self-loading of AH configs anymore.
  * Let's create an ADDR ticket for this ↑ non-backward compatible change.

**Comment by mseaton** [comment]
If we are removing a feature like this from AH, then we should bump the version to 3.0.0, not just up to 2.16.0.

**Comment by mks-d** [comment]
Thanks @mseaton and for [the exchange on Slack](https://openmrs.slack.com/archives/C021QUDSD5K/p1697473045708299), I have updated the description accordingly.

**Comment by Ruhanga** [comment]
I've created [ADDR-129](https://issues.openmrs.org/browse/ADDR-129) to followup the necessary refactoring on the AH module.

**Comment by mks-d** [comment]
@Ruhanga was this not completed in the end?
