### ISSUE TITLE
Liquibase loading fails when trying to execute sqlFiles relative to changset

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#255]
Due to Liquibase upgrades, when using the existing Liquibase domain in OpenMRS versions 2.5+, relative files referenced in changesets are not able to be found.

This was fixed in core in https://issues.openmrs.org/browse/TRUNK-6077, and requires some changes that are specific to this version to work in OpenMRS 2.5+.  Specifically, liquibase files passed in need to be paths that are relative to the OpenMRS application data directory.

**Comment by mseaton** [comment]
@mks-d / @ibacher / @Ruhanga / @rbuisson - see PR here:  https://github.com/mekomsolutions/openmrs-module-initializer/pull/256

**Comment by mks-d** [comment]
Thanks a bunch @mseaton 💪 🙏
