### ISSUE TITLE
Concepts domain to support updating concept datatypes to numeric.

### ISSUE THREAD

**Issue by Ruhanga** [mekomsolutions/openmrs-module-initializer#257]
Currently it is not possible to update concepts that are worthy updating to the `Numeric` datatype. Say for example, changing existing `Text` to `Numeric`.

With this Issue resolved, it should be possible to convert concepts such as are of the `Text` datatype to `Numeric` datatype.

Related to [HSC-190](https://mekomsolutions.atlassian.net/browse/HSC-190)

[HSC-190]: https://mekomsolutions.atlassian.net/browse/HSC-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mks-d** [comment]
@Ruhanga can this issue be closed?

**Comment by Ruhanga** [comment]
Yes @mks-d. Closing it.
