### ISSUE TITLE
Spring context to shutdown before subsequent Validator invocations.

### ISSUE THREAD

**Issue by Ruhanga** [mekomsolutions/openmrs-module-initializer#265]
In the context of the [OpenMRS Packager plugin](https://github.com/openmrs/openmrs-contrib-packager-maven-plugin), when the Validator is used more than once during the same Maven build, the current Spring context is carried over and reused during subsequent validations (given there are more than one submodules requiring validation.)

Since some runtime properties may need to change across invocations (such as database connection properties for example), it is critical that the Spring context is properly shutdown carried prior to subsequent Validator invocations.

**Comment by mks-d** [comment]
@Ruhanga this is fixed right?
