### ISSUE TITLE
Add support for installing Location Attribute Types via Initializer

### ISSUE THREAD

**Issue by mogoodrich** [mekomsolutions/openmrs-module-initializer#45]
* Support having a locationAttributeType.csv for setting up location attribute types.  Should support setting up the uuid, name, description, datatype and datatype config.

* Update the location loader so that location attribute type values can be set within the location.csv. 

* if it’s easy to make a generic feature to support multiple attribute data types we should add this, but otherwise just supporting FreeextDateType for now is fine.

Thoughts @mks-d ?

fyi @brandones @mseaton

**Comment by mseaton** [comment]
@mogoodrich I think this is already supported in the generate "attributetypes" domain.
https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/atttypes.md

**Comment by mogoodrich** [comment]
Yeah @mseaton  I was just reading your other comment and realized I missed this...

My mistake, I'm used to documentation scarity within OpenMRS so I just looked in the code for a LocationAttributeType handler, I didn't look at the README... :)

Closing this out.
