### ISSUE TITLE
Unable to use openmrs module initializer for provider management

### ISSUE THREAD

**Issue by rasikajare05** [mekomsolutions/openmrs-module-initializer#59]
In openmrs->Providers->Manage Providers -> Edit provider there is a functionality to set provider attributes for users i.e “Available for appointments” when we set this to ‘True’ then that user is available in Appointment Scheduling Module as a Provider.
This functionality is working fine in openmrs but could not find a way to do the same with openmrs module initializer.
Is there any way to import provider management through openmrs module initializer?

![Screenshot from 2020-04-12 18-37-13](https://user-images.githubusercontent.com/59169828/79092993-5a1ed280-7d70-11ea-8094-809e1d62bdd7.png)

**Comment by mks-d** [comment]
Hi @rasikajare05, Iniz intentionally limits itself to _metadata_. It looks like that the only thing that could be managed here are provider attributes (and they are indeed already supported).
