### ISSUE TITLE
Initializer doesn't support non-Java locales

### ISSUE THREAD

**Issue by mogoodrich** [mekomsolutions/openmrs-module-initializer#63]
When loading in messages.properties files, Iniz parses the locales for each of the files and validates that each locale is in the "available locales" list:

https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java#L177

This test confirms that the locale in the list of Java support locales:

https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html

I'd like to submit that this is to restrictive, and we should be able to drop this check entirely.  In the PIH-EMR we use the Haitian Kreyol locale ("ht") and define a "messages_ht.properties" file.  Even though this is evidently not a "supported" locale in Java, it has worked fine with our OpenMRS implementation, but, unfortunately, fails with Iniz because it is flagged as invalid.

**Comment by mogoodrich** [comment]
PR here: https://github.com/mekomsolutions/openmrs-module-initializer/pull/64

**Comment by mks-d** [comment]
Thanks @mogoodrich .

**Comment by mogoodrich** [comment]
Thanks @mks-d !
