### ISSUE TITLE
attribute type values are not filled if they are not created by Iniz

### ISSUE THREAD

**Issue by ahammi** [mekomsolutions/openmrs-module-initializer#66]
I try to load new concepts with attribute type values. Those attribute types already exist in openmrs (they have been created by another module). Concepts are created but attribute type values were empty. 

It looks like attribute types have to be inserted by Iniz in the same time as concepts ?

Here is an example of my csv file : https://pastebin.com/rWBcr8Vx

all attribute types referred in csv file can be created using this script : https://pastebin.com/jdgVU6h7

Thanks for your support.

**Comment by mks-d** [comment]
@ahammi, @samuelmale is still looking into it but two issues, see below:
| Same as mappings                                              | Data class        |
|---------------------------------------------------------------|-------------------|
| `DHIS2-DataElement:eYEWWggBSeG DHIS2-CategoryCombo:lQHfNtbk6vG` | `DHIS2-DataElement` |

1. I believe that the 'same as' mappings should be "`;`"-separated and not space-separated.
1. The error that we got is that the concept data class "DHIS2-DataElement" did not exist in our environment, what is creating it for you?

**Comment by samuelmale** [comment]
I have tested this out and I have it working. However apart from the non existing concept data class "DHIS2-DataElement" issue, the concept mapping sources `DHIS2-DataElement` and `DHIS2-CategoryCombo` are also non existing. 

Screenshot of the concept created with it's attributes set:

![screencapture-localhost-8080-openmrs-dictionary-concept-htm-2020-06-03-16_25_23](https://user-images.githubusercontent.com/26084581/83642356-688eab00-a5b7-11ea-9027-28a67218c59c.png)

**Comment by ahammi** [comment]
@mks-d @samuelmale , you are right the problem comes from same mapping as, it should be ; separated !  but somehow I didn't see the exception before ! sorry for confusing you. 
Many thanks.
