### ISSUE TITLE
Fails to import a form's translations when the version is other than 1

### ISSUE THREAD

**Issue by mupagasi** [mekomsolutions/openmrs-module-initializer#75]
**Problem description**: 
I have created a form using Form Builder and added French translations. When I edit the form and publish it, Form Builder creates a new version of that form. When I export it and load via Iniz, it fails to load the translations.

**The issue**: 
OpenMRS Initializer module fails to import form with its translation, when the form is in a version other than 1.

This is the error I get when I try to load the form on a fresh Bahmni instance:
![image](https://user-images.githubusercontent.com/19669911/89169183-2fa29080-d57e-11ea-9f26-3757d4f12712.png)

**Steps to reproduce on a fresh installation**:
1. Create form using Form Builder and publish it
2. Edit that form and add one or two concepts. This operation will create the second version of this form
2. Save the form and publish it for the second time
3. Now add French translation to the form
4. Export the form
5. Drop the exported JSON file to **bahmniforms/** folder in your OpenMRS Config
6. Start a clean/empty Bahmni instance and wait for Initializer to start importing `bahmniforms` contents
8. Check and confirm that the form has been created but it fails to load the translation, therefore preventing to display it.

**Comment by mks-d** [comment]
@chinzou do you know if this ticket is still current?

**Comment by chinzou** [comment]
I think not, this should've been fixed already by an upgrade of **bahmni.ie.apps** dependency
