### ISSUE TITLE
Bundle a standalone validator tool

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#84]
#### Background
See this seed Slack conversation: https://openmrs.slack.com/archives/CPC20CBFH/p1582575953010600

**Comment by mks-d** [comment]
@ibacher about your suggestion [here](https://github.com/mekomsolutions/openmrs-module-initializer/pull/88#pullrequestreview-555505458):
>I wonder if it makes sense to also provide a `--include.<domain>` flag to whitelist the specific files from a domain.

Sure, however what do you think should happen when `--exclude.<domain>` and `--include.<domain>` contradict each other?

**Comment by ibacher** [comment]
@mks-d For consistency, it might make sense to just have the `—include.<domain>` flag with the same `!` to switch to exclude mode. Alternatively, I’d just raise an error if both `—include` and `—exclude` were specified for the same domain without making any attempt to analyse if they contradict one another. Basically, I still think the model of “you’re either specifying a white-list or a black-list” is probably sufficient.
