### ISSUE TITLE
Enable htmlforms domain to set published and retired, and load from subdirectories

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#86]
This issue is for making the following enhancements to the newly added htmlforms domain:

* Support configuring the form.published property
* Support configuring the form and htmlform retired property
* Support for organizing htmlform xml files in subdirectories within the htmlforms domain

This will provide the ability to more fully manage forms, and to enable the ability to organize forms based on implementation preferences.

**Comment by mseaton** [comment]
@mks-d - if you could have a look at this and see what you think that would be very helpful.

**Comment by mks-d** [comment]
@mseaton this PR is an attempt to handle the part "should handle subdirectories": https://github.com/mekomsolutions/openmrs-module-initializer/pull/91

However what's happening to the URI to the HTML form though?

**Comment by mseaton** [comment]
@mks-d - that's cool - great to see that subdirectory support enabled broadly!  Not sure what you mean by the URI to HTML form?  What URI?

**Comment by mks-d** [comment]
What I meant is when implementations use HFE UI's `definitionUiResource`. For instance here for the ENTER mode: https://github.com/openmrs/openmrs-module-htmlformentryui/blob/e7b839235797b13f5d859b6cc16bdb3e06af46e5/omod/src/main/java/org/openmrs/module/htmlformentryui/page/controller/htmlform/BaseEnterHtmlFormPageController.java#L62

As you may recall the Ref App encourages the use of such URIs (see [here](https://github.com/openmrs/openmrs-module-referenceapplication/blob/8ac084672ac56643c169341fb879b9942105fe4d/omod/src/main/resources/apps/visitActions_extension.json#L7)):
```url
/openmrs/htmlformentryui/htmlform/enterHtmlFormWithStandardUi.page?...
  &definitionUiResource=referenceapplication:htmlforms/simpleVisitNote.xml
```
When forms are nested within the providing module's OMOD resources then this `definitionUiResource`'s value must reflect that nesting, for instance URIs like:
```url
definitionUiResource=acmemodule:htmlforms/ncd/initialScreening.xml
```
for NCD forms that have been nested inside such folder: `omod/src/main/webapp/resources/htmlforms/ncd`.

----

What's your take in regards to migrating to a config forms that are being referred to with such URIs currently?

**Comment by mseaton** [comment]
Ah, I see.  This is already supported, we added support for this to uiframework a few months ago or so.  You can do something like this now, and things work:

definitionUiResource=file:configuration/htmlforms/my-form.xml

My initial commit for this was here:
https://github.com/openmrs/openmrs-module-uiframework/commit/903e8f28be44614ed336506f094ab623ac13998a

We made some changes subsequently to tighten up security (eg. limit only to files within the .OpenMRS/configuration directory, eg. @ibacher made this recent commit:

https://github.com/openmrs/openmrs-module-uiframework/commit/f8c47da21127bf37950ce930a945bb5f8ffbd4ae

**Comment by mks-d** [comment]
That's amazing, thanks both @ibacher and @mseaton 👍
