### ISSUE TITLE
display:xy column to load UIFR-compatible i18n messages code and value pairs

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#95]
#### 1) Background
REST WS is able to fill in a `display` property whose value is the L10n of the metadata. REST WS is trying several routes of L10n, and one of them is the UIFR pattern described [here](https://talk.openmrs.org/t/i18n-support-for-all-classes-extending-baseopenmrsmetadata/26218/25?u=mksd). This means that if a UIFR pattern-compliant message has been loaded then REST WS will populate `display` accordingly.
* Full reference: '[I18n support for all classes extending BaseOpenmrsMetadata](https://talk.openmrs.org/t/i18n-support-for-all-classes-extending-baseopenmrsmetadata/26218/24?u=mksd)'

#### 2) Acceptance Criteria
Let us take the 'locations' domain as an example.

| <sub>UUID</sub>                                 | <sub>Name</sub>           | <sub>Display:en</sub>        | <sub>Display:fr</sub>          | <sub>Display:kh</sub>          | <sub>Description</sub>                                                                                                                 | <sub>...</sub> |
|--------------------------------------|----------------|----------------|----------------|------------------|-----------------------------------------------------------------------------------------------------------------------------|-----|
| <sub>eb96c0d4-6248-476b-a079-0aaabfa2f614</sub> | <sub>Emergency Room</sub> | <sub>Emergency Room</sub> | <sub>Salle d'urgences</sub> | <sub>បន្ទប់​សង្គ្រោះ​បន្ទាន់</sub> | <sub>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</sub> | <sub>...</sub> |

This should ensure that the following i18n code-values are loaded in memory:
##### 1. For locale 'en':
```
ui.i18n.Location.name.eb96c0d4-6248-476b-a079-0aaabfa2f614=Emergency Room
```
##### 2. For locale 'fr':
```
ui.i18n.Location.name.eb96c0d4-6248-476b-a079-0aaabfa2f614=Salle d'urgences
```
##### 3. For locale 'kh':
```
ui.i18n.Location.name.eb96c0d4-6248-476b-a079-0aaabfa2f614=បន្ទប់​សង្គ្រោះ​បន្ទាន់
```

**Comment by mks-d** [comment]
@ibacher, FYI @Ruhanga is starting work on this. This means that down the line we will want to make sure that the FHIR2 module supports this pattern as well whenever it returns an OpenMRS metadata name. What's your thoughts on this?

**Comment by ibacher** [comment]
I think we need to have some discussion around this. In principle, I'm fine with loading metadata display names from a Spring message source. I'm a little less thrilled by the idea of locating those by `ui.i18n`. I much prefer the original proposal of the OMRS class name + UUID. We'll also need to talk about where we are setting this in the FHIR model. In several places, we're constrained to only a single human usable "name" for something. We can probably use the standard [translation extension](https://www.hl7.org/fhir/extension-translation.html), but we might need a custom extensions in some cases.

We should also figure out how we communicate the necessary language to the FHIR2 module. Initially, with concepts, we were just returning every valid translation, but that winds up producing a large resource. It would be good if we can rely on the frontend to set the `Accept-Language` header appropriately.

**Comment by mks-d** [comment]
>I much prefer the original proposal of the OMRS class name + UUID.

That's totally fine with me btw, as long as both REST WS and FHIR2 support the Iniz-loaded formats. For now we are sticking with what REST WS already supports, but there is no harm in loading multiple i18n keys. So for instance having both for 'en'
* `ui.i18n.Location.name.eb96c0d4-6248-476b-a079-0aaabfa2f614=Emergency Room`
* `org.openmrs.Location.eb96c0d4-6248-476b-a079-0aaabfa2f614=Emergency Room`
