### ISSUE TITLE
Locations specified with a parent that doesn't exist should throw an IllegalArgumentException

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#98]
The fix should be made here: https://github.com/mekomsolutions/openmrs-module-initializer/blob/3de7a4afd0acdffaa5c784440301d8577f10ff33/api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java#L70

**Comment by icrc-psousa** [comment]
PR: [99](https://github.com/mekomsolutions/openmrs-module-initializer/pull/99)
